#pragma once
#define LAZY_IMPORTER_RESOLVE_FORWARDED_EXPORTS
#define WIN32_LEAN_AND_MEAN
#include <iostream>
#include <vector>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <unordered_set>
#include <string>
#include <list>
#include <random>
#include <fstream>
#include <Windows.h>
#include <conio.h>
#include <winternl.h>
#include <algorithm>
#include <functional>

#include <spdlog/spdlog.h>
#include "pe_bliss.h"
